"use client"

import React, { useState, useEffect } from 'react';
import axios from 'axios';
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/Components/Layout/Header";
import Newsletter from "@/Components/Layout/Newsletter";
import Navigation from "@/Components/Layout/Navigation";
import HomeComponent from '../Pages/Home'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const BASE_URL = process.env.NEXT_PUBLIC_APP_BASE_URL
  const [categories, setCategories] = useState([])
  const [categoryId, setCategoryId] = useState("");
  const [subcategories, setSubcategories] = useState([])




  const fetchSubcategories = async () => {
    console.log(categoryId,"categoryid")
    try {
      const response = await axios.get(`${BASE_URL}/subcategories/categories/${categoryId}`)
      console.log(response.data, "subcategories")
      setSubcategories(response.data)
      // console.log(response.data.categoryId, "categoryid")
    } catch (error) {
      console.error('Error fetching subcategories:', error);

    }
  }



  const fetchcategories = async () => {
    try {
      const response = await axios.get(`${BASE_URL}/categories`)
      console.log(response.data, "categories");
      setCategories(response.data)
        (response.data.map((category) => {
          console.log(category._id, "categorydivhdjvbcaj")
          setCategoryId(category._id);
          return category._id;
        }));
    } catch (error) {
      console.error('Error fetching categories:', error);

    }
  }



  useEffect(() => {
    fetchcategories();
  }, []);



  useEffect(() => {
    fetchSubcategories();
  }, [categoryId]);



  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <Navigation categories={categories} subcategories={subcategories} categoryId={categoryId}/>
        {children}
        <Newsletter />

      </body>
    </html>
  );
}
