
"use client"

import axios from "axios";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/Components/Layout/Header";
import Newsletter from "@/Components/Layout/Newsletter";
import Navigation from "@/Components/Layout/Navigation";
import HomeComponent from "../Pages/Home";
import { ToastContainer, toast } from "react-toastify";
import MobileApp from "@/Components/Home/MobileApp";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {





  return (
    <html lang='en'>
      <body
        className={` antialiased`}
      >
        <Header />
        <Navigation />
        {children}
        <MobileApp/>
        <Newsletter />
      
      </body>
    </html>
  );
}
